FROM openjdk:8-jdk-alpine as builder

RUN apk add --no-cache ca-certificates git

WORKDIR /usr/src/reportportal

COPY gradle/ ./gradle
COPY gradlew .
RUN ./gradlew wrapper

COPY build-quality.gradle build.gradle gradlew settings.gradle gradle.properties ./
RUN ./gradlew resolveDependencies

COPY . .
RUN ./gradlew build

FROM openjdk:8-jre-alpine

ENV JAVA_OPTS="-Xmx256m -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_APP=/service-jira.jar

RUN echo $'#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh

VOLUME /tmp

COPY --from=builder /usr/src/reportportal/build/libs/$JAVA_APP .
RUN sh -c 'touch $JAVA_APP'
EXPOSE 8080
ENTRYPOINT ["/start.sh"]
